<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%" id="AutoNumber1">
  <tr>
    <td colspan="3" bgcolor="#33CC33" align="center" style="padding:4px"><b>
    <span style="font-size: 12.0pt; line-height: 115%; font-family: Arial; color: white; text-shadow: auto">
    Nova Diretoria da SBRAFH tomou posse no último dia 02 de abril.</span></b></td>
  </tr>
  <tr>
    <td colspan="3" style="padding:10px">
    <p align="justify">
    <span style="font-size: 11.0pt; line-height: 115%; font-family: Arial">A 
    SBRAFH tem nova Diretoria desde o último dia 02 de abril. A posse ocorreu em 
    São Paulo, em cerimônia marcada pela renovação de compromissos com a 
    farmácia hospitalar brasileira.</span></td>
  </tr>
  <tr>
    <td width="100%" colspan="3">
    <p align="center">
    <img border="0" src="<?=$this->baseUrl?>/public/news/posse_1.jpg" width="600" height="185"></p>
    <p align="justify">
    <span style="font-size: 9.0pt; line-height: 115%; font-family: Arial">
    Diretoria da SBRAFH (acima, da esquerda para direita): Dra. Heloisa Arruda 
    Gomm Barreto (PR), Vice-Diretora Executiva; Dra. Ilenir Tuma Leão (GO), 
    Diretora Executiva; Dra. Helaine Carneiro Capucho (SP), Presidente; Dra. 
    Simone Dalla Pozza Mahmud (RS), Vice-Presidente; Dra. Mabel Mendes 
    Cavalcanti (RN), Diretora Finaceira; Dra. Carolina Raslan Dinis (MG), 
    Vice-Diretora Financeira. A Diretoria conta, ainda, com o conselho fiscal 
    composto por Dra. Maria das Dores Graciano Silva (MG), Dr. Mario Borges Rosa 
    (MG), Dra. Tatiana Amancio Campos (CE), Dra. Vanusa Barbosa Pinto (SP).</span></td>
  </tr>
 </table>
 <br />
 <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%" id="AutoNumber1">
  <tr>
    <td valign="top" style="width:33%;padding:0 10px">
    <p align="center">
    <img border="0" src="<?=$this->baseUrl?>/public/news/posse_2.jpg" width="114" height="172"></p>
    <p class="MsoNormal" style="margin-top:0cm;margin-right:7.05pt;margin-bottom:
0cm;margin-left:14.2pt;margin-bottom:.0001pt;text-align:justify;line-height:
normal"><span style="font-size:9.0pt;font-family:Arial">Dra. Eugenie Desirèe 
    Rabelo Néri (foto acima), Presidente da SBRAFH biênio 2010-2011, transmitiu 
    votos de uma gestão profícua à nova Diretoria, celebrando avanços 
    importantes em sua gestão. </span></td>
    <td valign="top"  style="width:33%;padding:0 10px">
    <p align="center">
    <img border="0" src="<?=$this->baseUrl?>/public/news/posse_3.jpg" width="182" height="172"></p>
    <p align="justify">
    <span style="font-size: 9.0pt; line-height: 115%; font-family: Arial">Dr. 
    Marcelo Polacow (foto acima) Conselheiro Federal pelo Estado de SP, 
    representando o Presidente do CFF, Dr. Walter Jorge João, discursou sobre a 
    trajetória vitoriosa dos farmacêuticos hospitalares e a importância da 
    farmácia hospitalar.</span></td>
    <td valign="top"  style="width:34%;padding:0 10px">
    <p align="center">
    <img border="0" src="<?=$this->baseUrl?>/public/news/posse_4.jpg" width="119" height="172"></p>
    <p align="justify">
    <span style="font-size: 9.0pt; line-height: 115%; font-family: Arial">Dra. 
    Helaine Capucho (foto acima), falou sobre a importância do momento para a 
    qualificação da assistência farmacêutica no sistema de saúde brasileiro, do 
    compromisso da nova Diretoria de aproximar a SBRAFH dos farmacêuticos 
    hospitalares e ressaltou o excelente trabalho realizado pela Diretoria 
    presidida pela Dra. Eugenie Néri.</span></td>
  </tr>
 </table>
 
 <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%" id="AutoNumber1">

  <tr>
    <td colspan="2" style="padding-top:24px">
    <p align="center">
    <img border="0" src="<?=$this->baseUrl?>/public/news/posse_5.jpg" width="414" height="198"></td>
    <td style="padding:0px 20px;padding-bottomn:16px">
    <p align="justify"">
    <span style="font-size: 9.0pt; line-height: 115%; font-family: Arial">Novos 
    Presidentes durante a posse em São Paulo (ao lado, da direita para 
    esquerda): Dra. Maely Peçanha Fávero Retto (Regional RJ), Dra. Helaine 
    Carneiro Capucho (Nacional), Dra. Áquila Serbate Borges (Regional MG) e Dr. 
    Pablo de Moura Santos (Regional BA).</span></td>
  </tr>
   <tr>
    <td colspan="2" style="padding-top:24px">
    <p align="center">
    <img border="0" src="<?=$this->baseUrl?>/public/news/posse_6.jpg" width="414" height="277"></td>
    <td style="padding:0px 20px;padding-bottomn:16px">
    <p align="justify"">
    <img border="0" src="<?=$this->baseUrl?>/public/news/posse_7.jpg" width="247" height="159">
	 <span style="font-size: 9.0pt; line-height: 115%; font-family: Arial">
			Autoridades presentes na cerimônia de posse. Ao lado, Dr. Marcelo Polacow Bisson (Conselheiro Federal pelo CRF-SP), 
		 Dr. Ademir Valério da Silva (Presidente da Anfarmag), Dra. Marcia Gutierrez (Presidente da Associação Brasileira de 
		 Farmacêuticos Homeopatas), Dra. Helaine Capucho, Dr. Pedro Eduardo Menegasso (Presidente do CRF-SP) e Dr. Marcos Machado 
		 Ferreira (Diretor-Tesoureiro do CRF-SP). Acima, Dr. Lindemberg Costa (Diretor de Assistência Farmacêutica da Secretaria 
		 de Saúde do Estado da Bahia) e Dra. Helaine Capucho.
	 </span></td>
  </tr>
 
  <tr>
  	<td colspan="3">&nbsp;</td></tr>
  <tr>
    <td colspan="3" align="center" bgcolor="#33CC33" style="padding:4px">
    <span style="font-size: 9.0pt; line-height: 115%; font-family: Arial; color: white"><strong>
    A SBRAFH está cada vez mais próxima de você: siga-nos no Twitter e curta-nos 
    no Facebook.</strong></span></td>
  </tr>
</table>
