<?
header("Cache-Control: no-store, no-cache, must-revalidate");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
?>


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1" />
		<title>SBRAFH - Sociedade Brasileira de Farmacia Hospitalar e Serviços de Saúde</title>
		<!-- 
		<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl?>/public/styles/style.css" />
		 -->
		
		<?php echo $this->headLink()->appendStylesheet($this->baseUrl . '/public/styles/style.css') ?>
		<script type="text/javascript" src="<?=jsLib?>/jquery-1.3.2.js"></script>
		<script type="text/javascript" src="<?=jsLib?>/prototypes.js"></script>
		<script type="text/javascript" src="<?=jsLib?>/jquery.maskedinput-1.2.2.min.js"></script>
		<link type="text/css" href="<?=jsLib?>/themes/base/ui.all.css" rel="stylesheet" />
		<script type="text/javascript" src="<?=jsLib?>/ui/ui.datepicker.js"></script>
		<script type="text/javascript" src="<?=jsLib?>/ui/ui.core.js"></script>

		<script language="javascript">
			var imagesDir = "<?=$this->baseUrl?>/public/wysiwyg/icons/"; // Images Directory
			var cssDir = "<?=$this->baseUrl?>/public/wysiwyg/styles/";	// CSS Directory
			var popupsDir = "<?=$this->baseUrl?>/public/wysiwyg/popups/";	// Popups Directory
			var wysiwygWidth = 440;
			var wysiwygHeight = 240;	// WYSIWYG Width and Height


			$(document).ready(function() {
				$('.text').focus(function(){$(this).css('background','#D2FABA')}).blur(function(){$(this).css('background','#F6DAB0')})
				$('.upper').blur(function(){$(this).val($(this).val().upper())})
				$('.lower').blur(function(){$(this).val($(this).val().lower())})

				$('.data').datepicker({  
					dateFormat: 'dd/mm/yy',  
					dayNames:['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],  
					dayNamesMin:['D','S','T','Q','Q','S','S','D'],  
					dayNamesShort:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],  
					monthNames:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],  
					monthNamesShort:['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],  
					nextText:'Próximo',prevText: 'Anterior'
					});
				
				$('#btSend').click(function(){
					if ($('#data').val()=='') {
						alert("Informe a data da notícia no formato DD/MM/AAAA !");
						$('#data').focus();
						return false;
						}			
					if ($('#titulo').val().trim().length == 0) {
						alert("Informe o título da notícia !");
						$('#titulo').focus();
						return false;
						}				
					if ($('#materia').val().trim().length == 0 && $('#link').val().trim().length == 0 && $('#arquivo').val().trim().length == 0) {
						alert("Digite a mátéria ou informe um link externo ou selecione um arquivo para envio !");
						$('#materia').focus();
						return false;
						}
					})	

				if($('#msg').val().length > 0 && $('#msg').val() != undefined) alert($('#msg').val());
				})
		</script>		
		<script type="text/javascript" src="<?=$this->baseUrl?>/public/wysiwyg/wysiwyg.js"></script>		
		
		<style>
			body{font-size:13px}
			form{font-size:13px}
			.label {font-size:13px;text-align:right;padding:0 4px}
			.text{width:440px;padding:2px 4px;background:#E0E4F9}
			.data{text-align:center;width:80px}
			span{margin:0 4px;font-size:13px;font-style:italic}
			.buttons{cursor:pointer}
			.buttons:hover{color:#f69;font-weight:bolder}
		</style>
	</head>
	<body>
		<form method="POST" name="noticia" action="<?=$this->action?>" ENCTYPE="multipart/form-data">
			<input type="hidden" name="uniqid" value="<?=$this->uniqid?>" />
			<input type="hidden" id="msg" value="<?=$this->message?>" />
			<input type="hidden" name="MAX_FILE_SIZE" value="8000000" />
			
			<table border="0" cellpadding="2" cellspacing="0">
				<tr>			
					<td class="label">Data:</td>
					<td>
						<input type="text" class="text data" maxlength="10" id="data" name="data" value="<?=$_POST['data']?>" />
					<td> 
					<td align=center><b>INFORMAÇÕES EXTRAS
				<tr>
					<td class="label">T&iacute;tulo:</td>
					<td><input type=text class="text" maxlength="255" id="titulo" name="titulo" value="<?=$_POST['titulo']?>" /></td>
					<td class="label">Fotógrafo:</td>
					<td><input type=text class="text" style="width:285px" maxlength="100" name="fotografo" value="<?=$_POST['fotografo']?>" /></td>
	
				</tr>
	
				<tr>
					<td class="label">Sub-t&iacute;tulo:</td>
					<td><input type=text class="text" maxlength="255" id="subTitulo" name="subTitulo" value="<?=$_POST['subTitulo']?>" /></td>
					<td class="label">url Foto:</td>
					<td><input type=file name="userFile" value="""></td>
				</tr>
	
				<tr>
					<td class="label">Mat&eacute;ria:</td>
					<td><textarea class="text" rows="14" name="materia" id="materia" /><?=$_POST['materia']?></textarea>
						<script>generate_wysiwyg('materia')</script>
	       		 </td>	
					<td class="label"></td>
					<td style="border:1px solid #eeeee4; width:200px; height:auto" align=center>
						<img src="/site/public/news/<?=$_POST['foto']?>" width="250" />
					</td>
				</tr>
	
				<tr>
					<td class="label">Fonte:</td>
					<td><input type=text class="text" maxlength="100" name="fonte" value="<?=$_POST['fonte']?>" /></td>
					<td class="label">Legenda:</td>
					<td rowspan="3">
						<textarea class="text" style="width:285px" rows="4" name="legenda" id="legenda" /><?=$_POST['legenda']?></textarea>
					</td>
				</tr>
				<tr>
					<td class="label">Cr&eacute;ditos:</td>
					<td><input type=text class="text" maxlength="100" name="credito" value="<?=$_POST['creditos']?>" /></td>
				<tr>
					<td class="label">Link:</td>
					<td><input type=text class="text" maxlength="100" name="link" value="<?=$_POST['link']?>" /></td>
				</tr>
				<tr>
					<td class="label">Arquivo:</td>
					<td><input type="file" class="text" maxlength="255" id="arquivo" name="arquivo" value="" /></td>
				</tr>
				<tr>
					<td class="label">Twitter:</td>
					<td colspan="3">
						<input type=text class="text" maxlength="100" name="twitter" id="twitter" value="<?=$_POST['twitter']?>" />
					</td>
				</tr>
				<tr>
					<td>
					<td height="25" align="center" colspan=3>
						<input type="submit" class="buttons" id="btSend" name="btSend" value="Enviar"/>
					</td>
			</table>
		</form>
	</body>
</html>
