<?php
$rs = $this->boleto;
$sacado = $rs->sacado;
$aluno = $rs->aluno;
//$db = Zend_Registry::get('db');
//$db->setFetchMode(Zend_Db::FETCH_OBJ);

//$this->fc->debug($rs);
if($rs->idCurso){
	$sql = "SELECT idAlunoCursos FROM alunoscursos WHERE (idCurso=$rs->idCurso) AND (idAluno=$rs->idCadastro)";
	$rs->idInscricao  = $this->fc->dbReader($this->db, $sql)->idAlunoCursos;
	}
else
	$rs->idInscricao = 0;

$action = "$this->baseUrl/boletos/save/curso/$rs->idCurso/inscricao/$rs->idInscricao/id/$rs->idFinanceiro";

?>
 
<link type="text/css" href="<?=jsLib?>/themes/base/ui.all.css" rel="stylesheet" />
<script type="text/javascript" src="<?=jsLib?>/ui/ui.datepicker.js"></script>
<script type="text/javascript" src="<?=jsLib?>/ui/ui.core.js"></script>
	
<script>
	$(document).ready(function(){
		hoje = new Date()
		dia = hoje.getDate()
		if (dia < 10) dia='0'+dia;
		mes = hoje.getMonth()+1;
		if (mes < 10) mes='0'+mes;
		ano = hoje.getFullYear();
		var hoje = ano+mes+dia;

		function toFloat(s){var t=s.replace('.','');t=t.replace(',','.');return parseFloat(t);}			
		


		$('.text').focus(function(){$(this).css('background','#E3EEF7')}).blur(function(){$(this).css('background','#fff')})
		$('.upper').keyup(function(){$(this).val($(this).val().upper())})
		$('.lower').keyup(function(){$(this).val($(this).val().lower())})	
		
		$('.data').datepicker({  
			dateFormat: 'dd/mm/yy',  
			dayNames:['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],  
			dayNamesMin:['D','S','T','Q','Q','S','S','D'],  
			dayNamesShort:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],  
			monthNames:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],  
			monthNamesShort:['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],  
			nextText:'Próximo',prevText: 'Anterior'
			});
			
		$('.valores').keyup(function(event){
			if (event.charCode && (event.charCode != 44 && event.charCode < 48 || event.charCode > 57)) {
				alert("Somente numeros por favor!\n\nUse ',' virgula para casas decimais");
				event.preventDefault();
				}
			valor = toFloat($('#valor').val());
			acrescimo = toFloat($('#acrescimo').val());
			total = eval(valor + acrescimo).toDecimal();
			$('#total').val(total);
			}); 	
		

			
		$('#btBaixa').click(function(){
			var alerta ="Verifique se está tudo correto para atualizar o registro.\n\n";
			alerta += "Caso a data de pagamento esteja preenchida, o status \n";
			alerta += "do registro será alterado para PAGO ou RECEBIDO\n";
			alerta += "Confirme a atualização do registro.\n\n";
			if($('#vcto').val()==''){alert('Digite a data de vencimento!');$('#vcto').focus();return false;}
			t = $('#vcto').val().split('/');
			vcto = t[2]+t[1]+t[0];
			//if($('#pgto').val()==''){alert('Digite a data de Pagamento!');$('#pgto').focus();return false;}
			//t = $('#pgto').val().split('/');
			//pgto = t[2]+t[1]+t[0];
			if(!confirm(alerta)) return false;
			return true;
			})
		$('#clear').click(function(){$('#pgto').val('00/00/0000')})
			
		if($('#msg').val().length > 0){			
			if($('#msg').val()=='Boleto atualizado com sucesso!')self.close();
			else alert($('#msg').val());
			}
		$('#btEmail').click(function(){
			if(!confirm('Enviar link para o email acima?')) return false;
			return true;
			})
			
		if($('#vcto').val()=='') $('#vcto').focus();	
		else $('#valor').focus();
		})
</script>		
	
<style>
	#baixa{width:100%;font:12px Arial, Helvetica, Sans-Serif, Tahoma, Verdana}
	#baixa caption{font-size:16px;font-weight:bolder;background:#6F8799;padding:4px;color:#fff}
	#baixa th{background:#A6BCCD;padding:4px;text-align:right;width:75px}
	#baixa td{border:solid 1px silver; padding:2px;}
	#baixa .button{cursor:pointer;font-weight:bolder}
	#baixa .button:hover{color:#f60}
	#baixa .data{width:80px;text-align:center}
	#baixa .valores{width:80px;text-align:right}
	#baixa .historico{}
	#baixa select{width:120px}
	#baixa .matricula{width:80px;text-align:center}
	#baixa .left{text-align:left}
	
</style>
<body>
<table cellspacing="0" cellpadding="0" border="0" width="100%">
	<tr>
		<td valign="top" class="palestras">
			<form name="fBaixa" id="fBAixa" method="POST" action="<?=$action?>">		
				<input type="hidden" id="msg" value="<?=$this->message?>"/>
				<table id="baixa" cellpadding="2" cellspacing="2" border="0" width="100%">
					<tr>
						<th nowrap>ID Fin.:</th>
						<td><?=sprintf("%06d",$rs->idFinanceiro)?></td>
						<th>Emissão:</th>
						<td><?=$this->fc->Ymd2dmY($rs->dataLct)?></td>
						<th>ID Cad.:</th>
						<td><?=sprintf("%06d",$rs->idCadastro)?></td>
						<th>ID Inscr.:</th>
						<td><?=sprintf("%06d",$rs->idInscricao)?></td>
					</tr>
				</table>
				

				<table id="baixa" cellpadding="2" cellspacing="2" border="0" width="100%">
					<caption>Dados do Aluno</caption>
					<tr>
						<th>Nome:</th>
						<td class='left'><?=$aluno->nome?></td>
						<th>CPF:</th>
						<td><?=$this->fc->formatCPF($aluno->cpf)?></td>
					</tr>
					<tr>
						<th>Endereço:</th>
						<td class='left'><?="$aluno->ender, $aluno->num  $aluno->compl"?></td>
						<th>CEP:</th>
						<td class='left'><?=$this->fc->formatCEP($aluno->cep)?></td>
					</tr>
					<tr>
						<th>Bairro:</th>
						<td class='left'><?=$aluno->bairro?></td>
						<th>Cidade:</th>
						<td class='left'><?="$aluno->cidade / $aluno->uf"?></td>
					</tr>
				</table>


				<table id="baixa" cellpadding="2" cellspacing="2" border="0" width="100%">
					<caption>Dados do Sacado</caption>
					<tr>
						<th>Nome:</th>
						<td class='left'><?=$sacado->nome?></td>
						<th>CPF:</th>
						<td><?=$this->fc->formatCPF($sacado->cpf)?></td>
					</tr>
					<tr>
						<th>Endereço:</th>
						<td class='left'><?="$sacado->ender, $sacado->num  $sacado->compl"?></td>
						<th>CEP:</th>
						<td class='left'><?=$this->fc->formatCEP($sacado->cep)?></td>
					</tr>
					<tr>
						<th>Bairro:</th>
						<td class='left'><?=$sacado->bairro?></td>
						<th>Cidade:</th>
						<td class='left'><?="$sacado->cidade / $sacado->uf"?></td>
					</tr>
				</table>
				
				<table id="baixa" cellpadding="2" cellspacing="2" border="0" width="100%">
					<caption>Dados do Boleto</caption>
					<tr>
						<th>Num. Docto.:</th>
						<td><?=$rs->numDoc?></td>
						<th>Vencimento:</th>
						<td><input type="text" readonly class="text data" name="vcto" id="vcto" value="<?=$this->fc->Ymd2dmY($rs->vcto)?>"/></td>
					</tr>
					<tr>
						<th>Valor R$</th>
						<td align="left">
							<input type="text" class="text valores" name="valor" id="valor" value="<?=number_format($rs->valor, 2, ',','.')?>"/>					
						</td>
						<th nowrap>(+) Juros R$</th>
						<td>
							<input type="text" class="text valores" name="acrescimo" id="acrescimo" value="<?=number_format($rs->acrescimo, 2, ',','.')?>"/>
						</td>
					</tr>
					<tr>

						<th>(=) Total R$</th>
						<td>
							<input type="text" readonly class="text valores" name="total" id="total" value="<?=number_format($rs->total, 2, ',','.')?>"/>
						</td>

						<th>Pagamento:</th>
						<td>
							<input type="text" readonly class="text data" name="pgto" id="pgto" value="<?=$this->fc->Ymd2dmY($rs->pgto)?>"/>
							<input type='button' id='clear' value=" Limpar ">
						</td>
					</tr>
					<tr>
						<th>Histórico:</th>
						<td colspan="3" class='left'>
							<input type="text" style="width:100%" class="text historico" name="historico"
								maxlength="100" id="historico" value="<?=substr($rs->historico,0,100)?>"/>
						</td>
					</tr>
					<tr>
						<th>Obsrvações:</th>
						<td colspan="3">
							<input type="text" style="width:100%" class="text historico" name="observacoes" id="observacoes" value="<?=$rs->observacoes?>" />
						</td>
					</tr>
					<tr>
						<th>Tipo Lcto:</th>
						<td>
							<select name="status" id="status" size="1" class="text">
								<option <?=($rs->status==1)?'selected':''?> value="1">A PAGAR</option>
								<option <?=($rs->status==2)?'selected':''?> value="2">A RECEBER</option>
								<option <?=($rs->status==3)?'selected':''?> value="3">PAGAS</option>
								<option <?=($rs->status==4)?'selected':''?> value="4">RECEBIDAS</option>
							</select>
						</td>
						<td colspan="2" style='text-align:center'>
							<b style='color:red'>ATENÇÃO: Digite virgula para separar decimais. Pontos serão desconsiderados</b><br />
						</td>
					</tr>
					<tr>
						<td colspan="4" style='text-align:center'>
							<input type="submit" name="btBaixa" id="btBaixa" class="button" value="Atualizar" />
						</td>
					</tr>
				</table>
			</form>
		</td>
	</tr>
</table>
