<style>
	.destaque{font-size:20pt;color:#f90;font-weight:bolder}
	.noticias{font-size:12px;color:#888;text-align:justify;padding:4px 0;border-bottom:solid 1px silver}
</style>
<table cellpadding="0" cellspacing="0" border="0" width="100%">
	<tr>
		<td valign="top">
			<table cellpadding="0" cellspacing="0" border="0" width="100%">
				<tr>
					<td colspan="3" style="padding-bottom:8px">
						<span class="destaque">destaque</span>
					</td>
				</tr>
				<tr>
					<td width="270">
						<a href="../congresso2011/" target="_congresso">
						<img src="<?=$this->baseImg?>/home/viiicongresso.jpg" border="0" width="280"
							style="margin-bottom:8px"></a><br />
						<p style="text-align:justify;font-size:12px;margin-right:10px">
						De 24 a 26/11/2011 aconteceu em Salvador-BA o VIII Congresso Brasileiro de 
						Farmácia Hospitalar. O evento contou com palestrantes nacionais e do exterior e 
						foi um enorme sucesso. A SBRAFH agradece a todos os congressistas, palestrantes e 
						toda equipe que trabalhou duro para que esse evento fosse o sucesso que foi.</p>
					</td>
					<td width="10">
					<td width="270" valign="top">
						<a href="#">
							<img src="<?=$this->baseImg?>/home/videocff.jpg" border="0" width="280" style="margin-bottom:8px"
								onclick="dialogModal('http://www.youtube.com/v/tZuMfk13Uag&hl=en', 'youtube', 380, 520)"></a><br />
						<p style="text-align:justify;font-size:12px;margin-right:10px"><b>Farmacêutico Hospitalar: Cuidando da sua saúde.</b><br />
						O Conselho Federal de Farmácia, através da Comissão de Farmácia Hospitalar, 
						presenteou os farmacêuticos hospitalares brasileiros com um vídeo lançado no 
						VIII Congresso Brasileiro de Farmácia Hospitalar, em Salvador. 
						Acesse o vídeo e utilize em suas apresentações.</p>
					</td>
				</tr>
			</table>
			
			<br />
			<br />
			<table cellpadding="0" cellspacing="0" border="0" width="100%">
				<tr>
					<td style="text-align:center"><img src="<?=$this->baseImg?>/bannerAssociados.jpg" border="0" /></td>
				</tr>
				<tr>
					<td style="text-align:center">
						<b style="color:#f90">Alguns Links são exclusivos para Associados, Congressistas, Patrocinadores ou Parceiros.</b><br />
						<small>Verifique no link histórico, a validade da sua anuidade e faça a renovação no prazo correto 
						para não perder os benefícios de associado.</small>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>			

