<p align="center">
<img border="0" src="<?=$this->baseImg?>/micromedex.jpg"></p>
<p align="center"><b><font face="Arial">Acesso ao MICROMEDEX:</font></b></p>
<p align="center">&nbsp;</p>
<p align="center"><b><font face="Arial">O acesso ao MICROMEDEX é restrito somente 
a associados SBRAFH ativos,<br>
ou seja, em dia com a sua anuidade.</font></b></p>
<p align="center">&nbsp;</p>
<p align="center"><b><font face="Arial">Caso não seja associado, clique no link 
Quero me Associar.</font></b></p>
<p align="center">&nbsp;</p>
<p align="center"><b><font face="Arial">Caso não esteja em dia com a sua 
anuidade,<br>
clique no link Renovar minha Inscrição.</font></b></p>
