<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=windows-1250">
  <meta name="generator" content="PSPad editor, www.pspad.com">
  <title></title>
  </head>
  <body>
	<form method="post" action="https://www.thomsonhc.com/home/dispatch/PFDefaultActionId/pf.LoginAction" name="login" id="login">
		<input type="hidden" name="ND_CPR" id="ND_CPR" value="Login" />
		<input type="hidden" name="CS" id="CS" value="287EEA" />
		<input type="hidden" name="DUPLICATIONSHIELDSYNC" id="DUPLICATIONSHIELDSYNC" value="4C3614" />
		<input type="hidden" name="login.username_index_0" value="BMHDS2" />
		<input type="hidden" name="login.password_index_0" value="trialmdx2" />
	</form>
		<script>document.getElementById("login").submit();</script>
	</form>
  </body>
</html>
