<style>
	#regras{margin-bottom:10px}
	#regras td{padding: 0 20px}
	#regras b{font-size:11pt}
	#regras ol{margin:6px 10px}
	#regras li{font-size:13px;margin-top:6px}
</style>
<table width='100%' border='0' cellpadding='2' cellspacing='2'/>
	<caption class="caption">Regras do Associado SBRAFH</caption>
</table>

<hr size="1">
<table id="regras" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td colspan="2">
			<b>TODO ASSOCIADO DA SBRAFH TEM DIREITO A:</b>
			<ol>
				<li>Enviar e receber informações e colaborar com as atividades relacionadas aos fins e objetivos da SBRAFH;</li>
				<li>Participar das Assembléias Gerais, bem como reuniões e oficinas de trabalho, com objetivo profissional ou científico, organizadas pela SBRAFH e obedecidos os requisitos da convocação;</li>
				<li>Participar e acompanhar a gestão da SBRAFH;</li>
				<li>Participar de iniciativas e programas culturais promovidos pela SBRAFH;</li>
				<li>Votar e ser votado para membro da Diretoria, do Conselho Fiscal e das Comissões Permanentes, em conformidade com o estatuto.</li>
			</ol>
		</td>
	</tr>
	<tr>
		<td><br />
			<b>TODO ASSOCIADO SBRAFH TEM O DEVER DE:</b>
			<ol>
				<li>Exercer sua atividade de acordo com a melhor prática existente;</li>
				<li>Colaborar com os propósitos da SBRAFH em todas as ocasiões em que estiver presente, fornecendo dados, publicações ou 
				trabalhos e conhecimentos científicos e profissionais;</li>
				<li>Contribuir com a sustentabilidade da SBRAFH, pagando a anuidade de manutenção;</li>
				<li>Acatar o estatuto, normas e acordos estabelecidos com outras entidades parceiras e com os órgãos de governo e entidades 
					reguladoras da atividade;</li>
				<li>Desempenhar com eficiência os cargos e comissões que lhe forem confiados.</li>
			</ol>
		</td>
		<td><img src="<?=$this->baseImg?>/sol.jpg" border="0"/></td>
	</tr>
</table>
