<style>
	#about{margin-bottom:10px}
	#about td{padding: 0 20px}
	#about .titulo{
		background:#f90;
		margin-top:20px;
		padding-left:24px;
		font-size:12pt;
		font-weight:bolder;
		text-decoration:underline}	
</style>

<table width='100%' border='0' cellpadding='2' cellspacing='2'/>
	<caption class="caption">Porque ser Associado SBRAFH</caption>
</table>

<hr size="1">

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td><img src="<?=$this->baseImg?>/razoes.jpg" border="0" style="border:solid 1px silver;margin-right:10px"></td>
		<td>
			<p style="line-height:160%">Tornar-se membro da Sociedade Brasileira de Farmácia Hospitalar e Serviços de Saúde (SBRAFH) 
			permite a você obter vários benefícios. <br /><br />
			Veja a seguir:</p>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="padding:6px 20px;font-size:14px">
			<ul>
				<li>Desconto no Congresso Brasileiro de Farmácia Hospitalar;</li>
				<li>Desconto na aquisição de publicações Sbrafh;</li>
				<li>Desconto na aquisição de publicações de empresas parceiras;</li>
				<li>Desconto em eventos apoiados pela Sbrafh;</li>
				<li>Ter acesso a um site moderno, dinâmico e com informações práticas;</li>
				<li>Ter acesso à área restrita para associados, com formulários e outros instrumentos práticos para download;</li>
				<li>Ter acesso à revista científica (RBFHSS) impressa e eletrônica: única revista especializada em Farmácia Hospitalar e 
				em Serviços de Saúde da América Latina;</li>
				<li>Possibilidade de realização da prova para obtenção do título de Especialista em Farmácia Hospitalar;</li>
				<li>Participar de uma entidade, sem fins lucrativos, que trabalha para fortalecer e defender a atividade de Farmácia Hospitalar no Brasil.</li>
			</ul>
		</td>
	</tr>
	<tr>
		<td rowspan="2"><img src="<?=$this->baseImg?>/razoes2.jpg" border="0" style="border:solid 1px silver;margin-right:10px"></td>
		<td style="background:#A4C3E9;text-align:center">
			<b style="font-size:20px">Participe!</b><br /><br />  
			<b style="font-size:14px">Venha, juntamente conosco, construir uma instituição sólida e que valoriza e representa a farmácia hospitalar, 
			que é um dos segmentos da profissão farmacêutica que mais se consolida na atualidade!</b>		
		</td>
	</tr>
</table>
