

<style>

	.cursosTopo{

		background:#599da1;

		border:0;

		padding-top:4px;

		color:#ffffff;

		text-align:center;

		height:24px;

		font-weight:bolder;

		font-size:14pt;

		letter-spacing:.1em;

		border-top-left-radius: 6px;

		border-top-right-radius: 6px;

		border-bottom-left-radius: 6px;

		border-bottom-right-radius: 6px;

		}

	.tituloCursos{

		background:#14b7cd;

		color:#ffffff;

		text-align:center;

		height:50px;

		font-weight:bolder;

		font-size:13pt;	

		border-top-left-radius: 6px;

		border-top-right-radius: 6px;

		border-bottom-left-radius: 6px;

		border-bottom-right-radius: 6px;

		}

</style>



<table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin-top:0px">

	<tr>

		<td>

			<div class="cursosTopo">CURSOS  PREVISTOS PARA  2017</div>

		</td>

	</tr>

</table>



						

				<!--	

				</tr>



				<tr>-->

				<td width="20" style="display:none">&nbsp;</td>

				<!--

				</tr>



				<tr>-->

					<td align="center" valign="top"

						style="padding:8px;;width:48%;

							background:#eeeee4;

							border-top-left-radius: 10px;

							border-top-right-radius: 10px;

							border-bottom-left-radius: 10px;

							border-bottom-right-radius: 10px;display:none">

						<p style="font-size:11px;text-align:justify">OBJETIVO:- Facilitar o acesso a qualificação do profissional, tendo como contrapartida a colaboração do monitor no suporte operacional necessário para manter e aprimorar a qualidade do curso oferecido.</p>

						<p style="font-size:11px;text-align:justify">NÚMERO DE VAGAS:- Serão oferecidas 2 vagas . O curso está sujeito à confirmação de sua data de início, podendo esta ser adiada, ou mesmo cancelada, em função de não ser atingido o número mínimo de inscritos para sua viabilização.</p>

						<!--<p	style="font-size:11px"><a href="<?=$this->baseUrl?>/index/monitores/">Clique Aqui</a> para mais informações.</p>-->

						<p	style="font-size:11px">Aguarde mais informações.

					</td>

				</tr>



				<tr>

					<td colspan="3">&nbsp;</td>

				</tr>			

				<tr>

					<td class="tituloCursos">ESPECIALIZAÇÃO</td>



				<tr>

					<td align="center" valign="top"

						style="padding:8px;

							background:#eeeee4;

							border-top-left-radius: 10px;

							border-top-right-radius: 10px;

							border-bottom-left-radius: 10px;

							border-bottom-right-radius: 10px">

						<a href="http://www.cmmg.edu.br/cursos/farmacia-clinica-e-farmacologia-aplicada-a-pratica-clinica/" style="text-decoration:none" target="cmmg">

						<b style="font-size:20px;color:#14b7cd">Farmácia Clínica e<br />Farmacologia Aplicada<br />à Prática Clínica</a></b><br />

						<p style="font-size:13px;margin:4px 0;display:none">ESPECIALIZAÇÃO - <i>LATO SENSU</i><br />

							<b style="color:#14b7cd;display:none">"O diferencial nos concursos públicos"</b>

						</p>

							<a href="http://www.cmmg.edu.br/cursos/farmacia-clinica-e-farmacologia-aplicada-a-pratica-clinica/" 

							style="text-decoration:none" target="cmmg"><img 

							src="<?=$this->baseImg?>/banner_23_de_setembro.jpg" border="0" width="600"/></a>

						</p>

						<p style="font-size:14px;margin:12px 0"><hr size="1" /></p>

						

						<!--

						<a href="<?=$this->baseUrl?>/cursos/open/id/158/" style="text-decoration:none">

						<b style="font-size:20px;color:#14b7cd">FARMÁCIA CLÍNICA</a></b>

						<p style="font-size:13px;margin:4px 0">ESPECIALIZAÇÃO - <i>LATO SENSU</i><br />

							<b style="color:#14b7cd">"O diferencial nos concursos públicos"</b>

						</p>

						<img style="margin:8px 0;" src="<?=$this->baseImg?>/inicio2.gif" border="0"/>

						<img style="margin:8px 0;" src="<?=$this->baseImg?>/vagas.gif" border="0"/>

						<p style="font-size:14px;margin:12px 0">

							Aguarde mais informações</p>

						-->	

						

						<!--

						<div style="font-size:12px;color:#a4a4a4;font-size:14px">Início previsto 20/05/2016<br />

						

							<a href="<?=$this->baseUrl?>/cursos/open/id/158/">

							<img src="<?=$this->baseUrl?>/public/images/inscricoesAbertas2.gif" border="0" /></a>

							

						</p>	-->					



					</td>

				</tr>



				<tr>

					<td colspan="3">

					</td>

				</tr>

			</table>

		</td>

	</tr>

</table>



<table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin-top:8px">

	<tr>

		<td colspan="3" style="text-align:left;padding:8px;text-align:center">

			<p class="titulo">Eventos da área (Parceiros)</p>

			<? if(date('Ymd') <= '20151114'):?>	

				<a href="http://www.sbrafh.org.br/congresso2015/" target="_parceiros">

					<img style="margin:8px 0" src="<?=$this->baseImg?>/banner_congresso_sbrafh.jpg" border="0" width="610"/></a>

			<? endif;?>



			<? if(date('Ymd') <= '20151003'):?>				

					<a href="https://sobrafo.websiteseguro.com/seminarios2015/" target="_cursos">

						<img src="<?=$this->baseImg?>/home/banner_seminarios_sobrafo_600x200.jpg" border="0" width="600" /></a>

			<? endif;?>

		</td>



</table>







<style>

	#layer {

		position:absolute;

		z-index:100;

		top:10px;

		left:200px;

		width:500px;

		height:728px;

		padding:0px;

		background:#fff;

		border:4px solid #599da1;

		border-radius: 10px;

		-moz-border-radius: 10px;

		-webkit-border-radius: 10px;

		display:none;

		}



	#layer p{padding:12px;font-size:13px}

	#layer .close {text-align:right;position:absolute;z-index:110;font-size:13px}

</style>





<script language="Javascript">

	$(document).ready(function() {

		$('#layer').css('left',(screen.width-500)/2+'px');

		$('#close').click(function() {

			$('#layer').css('display','none');

			})

		})	



</script>

<div id="layer">

	<div style="text-align:right;background:#599da1;padding-right:0px;margin:0;height:20px;font-size:11px">

		<a href="#" id="close"><b style="color:#fff">Fechar (X) </b></a>

	</div>

	<img src="<?=$this->baseImg?>/natal2014.jpg" border="0" width="500" />

</div>

