<style>
	.home{font-size:20pt;color:#f90;font-weight:bolder}
	.home{font-size:12px;color:#888;text-align:justify;padding:4px 0;border-bottom:solid 1px silver}
</style>
<table cellpadding="0" cellspacing="0" border="0" width="100%" class="home">
	<tr>
		<td align="center">Olá<br /><b><?=$this->user->nome?></b>,<br /><br />
			seja bem-vindo(a)!<br /><br /><br />
			<img src="<?=$this->baseImg?>/Login.gif" border="0" /><br /><br />
			Verifique no menu ao lado suas opções disponíveis.
		</td>
	</tr>
</table>			

