<style>
	#tcc{margin-top:10px;margin-right:10px;width:100%;font-size:13px}
	#tcc p{font-size:13px;text-align:justify;margin-bottom:8px;margin-left:8px}
	#tcc p.titulo{font-size:16px;font-weight:bolder;color:#14b7cd;text-align:center}
	#tcc ol li{font-size:13px;margin-bottom:8px}
</style>


<?php
$dataLimite = date("Y-m-d", time() + (86400 * 7)); // vai mostrar o ultimo dia do mes atual
//echo "dataLimite = $dataLimite";
if ($this->user->status > 0):
	if ($this->user->validade < date('Y-m-d'))
		$status = sprintf("<b>VENCIDA em %s</b> - $this->dataVal Clique no link Renovar minha Inscrição ao lado
			para gerar o Boleto da renovação da sua Inscrição.", $this->fc->ymd2dmY($this->user->validade));
	elseif($this->user->validade <= $dataLimite)
		$status = sprintf("<b>A VENCER EM %s</b> - Clique no link Renovar minha Inscrição ao lado
		para gerar boleto de renovação da sua inscrição.", $this->fc->ymd2dmY($dataLimite));
	else 
		$status = "<b>ATIVO - Nenhuma pendência de pagamento até o momento.</b>";
endif;	
//$this->fc->debug($this->user);
?>
<div id="tcc">

	<p class="titulo">CURSO DE ESPECIALIZAÇÃO <i>LATO SENSU</i><br>
		PENDÊNCIA TRABALHO DE CONCLUSÃO DE CURSO/TCC</p>
	
	<p align="justify">
		Os alunos reprovados ou que não apresentaram TCC, caso queiram, poderão se 
		rematricular na disciplina Elaboração de TCC até o dia 07/03/2014.</p>
	
	<p><b>Orientação TCC opções:</b></p>
	
	<ol>
	  <li align="justify">O aluno poderá indicar o orientador que deverá ser aprovado pela coordenação 
			do curso e unidade acadêmica certificadora.</li>
	  <li>A AMF indicará o orientador. Nesse, caso a linha de pesquisa será definida 
			pelo orientador</li>
	</ol>
	<p align="justify"><b>Observação</b>: O aluno deverá escolher a sua opção no ato da rematricula.<br>
	A confirmação do nome / contato do orientador e regras gerais serão encaminhadas 
	para o email do aluno até o dia 17/03/2014.</p>
	
	<p align="justify"><b>Data da apresentação do TCC</b>: A apresentação definitiva será agendada para o 
	período de 28 de abril  a 04 de maio de 2014. Caso o aluno tenha condições a apresentação 
	poderá ser antecipada.</p>
	
	<p><b>Valor da Disciplina Elaboração de TCC</b>: R$ 490,00</p>
	
	<p><b>Forma de pagamento:</b> Boleto bancário gerado no ato da rematricula no site 
	www.amfar.com.br/site/. Após o pagamento do boleto, favor digitalizar e enviar para o 
	email: <a href="mailto:mariadasdores@amfar.com.br">mariadasdores@amfar.com.br.</a></p>
	
	<p><b> Nota importante:</b> a regularização na disciplina de Elaboração do TCC não inclui a resolução de 
	pendências em outras disciplinas, frequência e /ou situação financeira.</p>
	
	<p><b>Informações:</b> mariadasdores@amfar.com.br ou 31 9866-9504</p>
	
	
	<script>
		$(document).ready(function(){
			$('#btSend').click(function(){
				if(!$('#tipo').is(':checked') && !$('#tipo2').is(':checked')){
					alert('Por favor, selecione quem indicará o Orientador.');
					return false;
					}
				
				if(!$('#concordo').is(':checked')){
					alert('Por favor, marque a caixa que leu e concorda com o regulamento.');
					return false;
					}
				})
			})
	</script>
	<form name="rematricula" id="rematricula" method="POST" action="">
		<input type="hidden" name="id" value="<?=$this->tcc->id?>" />
		<pre style="margin-left:8px">Id Cadastro Nº	: <?=sprintf("%06d", $this->user->idCadastro)?>
			<br />Cadastrado em	: <?=$this->fc->msql2dmY($this->user->dataReg, true)?>
			<br />Nome		: <?=$this->user->nome?>
			<br />Email		: <?=$this->user->email?>
			<br />Fone		: <?=$this->user->fone?>
			<br />Cel		: <?=$this->user->fone2?>
			<br />Curso		: <?=$this->tcc->curso?>
		</pre>
		<p style="background:#14b7cd;text-align:center;padding:2px 4px">
			<b style="color:#ffffff">Caso o título do curso acima não esteja correto, por favor entre em contato antes de continuar!</b>
		</p><?
		//$this->fc->debug($this->curso);
		if((int)$this->tcc->id > 0): ?>
			<input type="radio" name="orientador" id="tipo2" value="ALUNO" />Aluno indicará o Orientador<br />
			<input type="radio" name="orientador" id="tipo" value="AMF" />AMF indicará o Orientador<br /><br />
			
			
			<input type="checkbox" name="concordo" id="concordo">
				Declaro que li o regulamento acima e estou de acordo com os termos apresentados e que deverei pagar 
			 	a quantia de R$ 490,00.
			<p style="text-align:center">
				<input type="submit" name="btSend" id="btSend" value="<< Enviar >>" class="button" />
			</p><?
			if($this->boleto)
				echo"<p align='center'><a href='http://www.amfar.com.br/boletos/boleto.php?id=$this->boleto' target='_boleto'>Clique Aqui para imprimir o boleto</a></p>";
		endif; ?>
		
	</form>
</div>
