<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>AMF - Associação Mineira de Farmacêuticos</title>
		<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
		<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl?>/public/styles/style.css" />	
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery-1.3.2.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/prototypes.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery.maskedinput-1.2.2.min.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery.limit-1.0.source.js"></script>
		<link id="lnkRelShortCutIcon" rel="shortcut icon" href="<?=$this->baseImg?>/favicon.png" />

		<script language="javascript" type="text/javascript">
			 $(document).ready(function(){
				if ($.browser.msie) {
					}
				else {
					$('fieldset').css('border-width','1px');
					$('fieldset').css('border-color','#369');
					$('fieldset').css('-moz-border-radius','10px');
					$('fieldset').css('-webkit-border-radius','10px');
					$('fieldset').css('border-radius','10px');
					}

				$('.text').focus(function(){$(this).css('background','#E0E4F9')}).blur(function(){$(this).css('background','#fff')})
				$('.upper').keyup(function(){$(this).val($(this).val().upper())})
				$('.lower').keyup(function(){$(this).val($(this).val().lower())})				
				
				$('#btIndique').click(function(){
					if($('#namefrom').val().trim()==''){
						alert('Por favor digite seu nome!');
						$('#namefrom').focus();
						return false;
						}
					if($('#mailfrom').val().trim()==''){
						alert('Por favor digite seu email!');
						$('#mailfrom').focus();
						return false;
						}				
					if(!$('#mailfrom').val().validEmail()){
						alert('Por favor digite corretamente seu email!');
						$('#mailfrom').focus();
						return false;
						}
					if($('#uffrom').val()==''){
						alert('Por favor selecione seu estado!');
						$('#uffrom').focus();
						return false;
						}

					if($('#nameto').val().trim()==''){
						alert('Por favor digite o nome do(a) amigo(a)!');
						$('#nameto').focus();
						return false;
						}
					if($('#mailto').val().trim()==''){
						alert('Por favor digite o email do(a) amigo(a)!');
						$('#mailto').focus();
						return false;
						}				
					if(!$('#mailto').val().validEmail()){
						alert('Por favor digite corretamente o email do(a) amigo(a)!');
						$('#mailto').focus();
						return false;
						}
					if($('#ufto').val()==''){
						alert('Por favor selecione o estado do(a) amigo(a)!');
						$('#ufto').focus();
						return false;
						}
					})
				
				if ($('#msg').val()!='' && $('#msg')!= undefined) alert($('#msg').val());
				})

		</script>
		
		
		<style type="text/css">			
			#indique{font-family:Arial, Helvetica, Sans-Serif, Tahoma, Verdana;font-size:12px}
			#indique .label{text-align:right;padding:0 4px;font-size:12px;white-space:nowrap}
			#indique td{padding:0 4px;font-size:12px}
			#indique .button{cursor:pointer}
			#indique .button:hover{color:#f90}
			legend{padding:0 10px}
		</style>
	</head>

	<body style="background:#e4e4e4">
		<fieldset>
			<legend>Envie este link a seus amigos!</legend>
			<form action="" method="post" name="indique" id="indique">
				<input type="hidden" id="msg" value="<?=$this->message?>" />
				<table border="0" cellspacing="0" cellpadding="0" width="100%">
					<caption><br />Envie este link a seus amigos!</caption>
					<tr>
						<td align="center" colspan=2 class="tbCaption"><b style="color:#fff"><?= $titulo?></td></tr>
							
					<tr>
						<td class="label">Seu Nome:</td>
						<td>
							<input type="text" class="text upper" id="namefrom" name="namefrom" value="<?=$_POST['namefrom']?>" maxlength="50" />
						</td>
					</tr>
							
					<tr>
						<td class="label">Seu E-mail:</td>
						<td>
							<input type="text" class="text lower" name="mailfrom" id="mailfrom" value="<?=$_POST['mailfrom']?>" maxlength="80" />
						</td>
					</tr>
								
					<tr>
						<td class="label">Estado:</td>
						<td>
							<select name="uffrom" id="uffrom" size="1">						
								<option value="">Selecione o Estado</option><?
								foreach($this->estados as $rs):
									$selected = ($_POST['uffrom']==$rs->uf) ? 'selected' : null;
									echo"<option $selected value='$rs->uf'>$rs->estado</option>";
								endforeach; ?>
							</select>
						</td>
					</tr>
						
					<tr>
						<td align="center" colspan="2" nowrap>				
							<input type="checkbox" name="mailing" value="ON" checked>
								<b class="negrito">Autorizo o envio e E-mailing para o e-mail acima.</small>
						</td></tr>
						
					<tr><td colspan="2" style="padding:10px 0"><hr size=1"></td></tr>
						
					<tr>
						<td class="label">Amigo(a):</td>
						<td>
							<input type="text" class="text upper" id="nameto" maxlength="50" name="nameto" value="<?=$_POST['nameto']?>" />
						</td>
					</tr>
							
					<tr>
						<td class="label">E-mail:</td>
						<td>
							<input type="text" class="text lower" id="mailto" name="mailto" value="<?=$_POST['mailto']?>" maxlength="80" />
						</td>
					</tr>
			
					<tr>
						<td class="label">Estado:</td>
						<td>
							<select name="ufto" id="ufto" size="1">						
								<option value="">Selecione o Estado</option><?
								foreach($this->estados as $rs):
									$selected = ($_POST['ufto']==$rs->uf) ? 'selected' : null;
									echo"<option $selected value='$rs->uf'>$rs->estado</option>";
								endforeach; ?>
							</select>
						</td>
					</tr>				
			
					<tr>
						<td align="center" colspan="2" height="30"><br />
							<input type="submit" id="btIndique" name="btIndique" value="Enviar Link" class="button" />
						</td>
					</tr>
				</table>
			</form>
		</fieldset>
	</body>
</html>
