<style>
	.conheca{font-size:13px}
	.conheca p{text-align:justify;margin:8px;font-size:13px;line-height:150%}
	.conheca .blue{color:#369}
	.conheca ul{list-style-image:url('<?=$this->baseUrl?>/public/styles/seta.jpg')}
	.conheca ul li{margin:4px 0;line-height:150%;font-size:13px}
	.conheca .dest{font-size:14px;font-weight:bolder;color:#369;background:#D9E7F8;padding:1px 10px}
	.conheca p{text-align:justify;line-height:150%}
	.conheca .center{text-align:center}
</style>

<div class="conheca">
	<p>A <b>Associa&ccedil;&atilde;o Mineira de Farmac&ecirc;uticos (AMF)</b> 
		&eacute; uma entidade fundada desde <b>1922</b>, que por v&aacute;rios anos
		foi &oacute;rg&atilde;o m&aacute;ximo de representa&ccedil;&atilde;o
		dos farmac&ecirc;uticos em Minas Gerais.
	</p>
	
	<p>
		Atrav&eacute;s dela foram fundados o <b>Conselho Regional de Farm&aacute;cia</b>
		e o <b>Sindicato dos Farmac&ecirc;uticos do Estado de Minas Gerais</b>
	</p>

	<p>
	 A partir de 1993, ap&oacute;s uma grande reforma, a <b>AMF</b>
	 vem crescendo e se fortalecendo e possui como principal objetivo o <b>Aprimoramento
	 T&eacute;cnico Cient&Iacute;fico</b> dos profissionais farmac&ecirc;uticos.
	 </p>

	<p>
	 Atualmente, a <b>AMF</b> vem trabalhando muito na organiza&ccedil;&atilde;o
	 de <b>cursos</b>, <b>congressos</b>, <b>comemora&ccedil;&otilde;es</b>
	 das datas importantes para a classe farmac&ecirc;utica, <b>participando</b>
	 de discuss&otilde;es dos diversos assuntos da &aacute;rea, <b>negociando conv&ecirc;nios</b>
	 interessantes e prestando <b>servi&ccedil;os de consultoria</b> 
	 em algumas &aacute;reas da farm&aacute;cia.</p>
	<br />

	<b class="dest">Nossa Missão:</b>
	<ul>
		<li>
		Representar os farmacêuticos hospitalares e em serviços de saúde, buscando seu reconhecimento 
		social, através do estímulo a qualificação profissional e ações de articulação política, 
		junto a sociedade e equipe multidisciplinar em saúde.</li>
	</ul>
	

	<br />
	
	<b class="dest">Nossa Visão:</b>
	<ul>
		<li>
			Ser referência internacional, para farmacêuticos e instituições, no segmento de hospitais e demais 
			serviços de saúde e cuidados farmacêuticos.</li>
	</ul><br />
	<b class="dest">Nossos Valores:</b>
	<ul>
		<li>Ética</li>
		<li>Compromisso</li>
		<li>Integridade</li>
		<li>Transparência</li>
		<li>Respeito</li>
		<li>Responsabilidade</li>
		<li>Conhecimento</li>
	</ul><br />
	
	<b class="dest">Perfil da Clientela:</b>
	<ul>
		<li>Farmacêuticos e estudantes de graduação em farmácia.</li>
	</ul>		

	<p>
		Para um crescimento maior da <b>AMF</b> &eacute; necess&aacute;rio
		uma grande participa&ccedil;&atilde;o do profissional farmac&ecirc;utico,
		atrav&eacute;s de sua associa&ccedil;&atilde;o e participação em nossos eventos.
	</p>

	<br />

	<p class="dest center">
		 Seja s&oacute;cio da AMF !<br />
		 A Associa&ccedil;&atilde;o precisa muito de voc&ecirc; !!!</b>
	</p>
	 
	<p><br /><b class="dest">Vantagens do Associado AMF:</b></p>
	<ul>
		<li>Participar de cursos de atualiza&ccedil;&atilde;o e especializa&ccedil;&atilde;o;</li>
		<li>Estabelecer interc&acirc;mbio cient&iacute;fico com colegas que atuam nas &aacute;reas afins;</li>
		<li>Ter benef&iacute;cios dos conv&ecirc;nios firmados com a AMF;</li>
		<li>Manter-se informado de todos os assuntos referentes a profiss&atilde;o e da &aacute;rea da sa&uacute;de.</li>
	</ul>
</div>
