<p style="text-align:center">
	A <b class="blue">AMF</b> está localizada em área privilegiada de fácil acesso.<br />
	Caso queira nos fazer uma visita, será uma honra receber-lhe.
</p>
<div style="text-align:center">
	<img src="<?=$this->baseImg?>/localizacao.jpg" border="0" />
</div>

<!--
<div style="text-align:center">
	<iframe width="640" height="500" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" 
		src="https://maps.google.com/?ie=UTF8&amp;ll=-19.918691,-43.959833&amp;spn=0.386696,0.617294&amp;t=m&amp;z=11&amp;output=embed"></iframe>
		<br /><small><a target="_google" href="https://maps.google.com/?ie=UTF8&amp;ll=-19.918691,-43.959833&amp;spn=0.386696,0.617294&amp;t=m&amp;z=11&amp;source=embed" 
		style="color:#0000FF;text-align:left">Exibir mapa ampliado</a></small>
</div>
-->

<p style="text-align:center; background:#000066; font-size:8pt; font-weight:bolder; color:#fff">
	AV. DO CONTORNO, 9215 - S. 502 - ED. HUMBERTO MARTINS VIEIRA - PRADO<br>
	CEP 30110-130 - BELO HORIZONTE - MG - TEL/FAX: 31 3291-6242</p>
</div>
