<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>AMF - Associação Mineira de Farmacêuticos</title>
		<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
		<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl?>/public/styles/style.css" />	
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery-1.3.2.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/prototypes.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery.maskedinput-1.2.2.min.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery.limit-1.0.source.js"></script>
		<link id="lnkRelShortCutIcon" rel="shortcut icon" href="<?=$this->baseImg?>/favicon.png" />

		<script language="javascript" type="text/javascript">
			 $(document).ready(function(){
				if ($.browser.msie) {
					}
				else {
					$('fieldset').css('border-width','1px');
					$('fieldset').css('border-color','#369');
					$('fieldset').css('-moz-border-radius','10px');
					$('fieldset').css('-webkit-border-radius','10px');
					$('fieldset').css('border-radius','10px');
					}
				$('.text').focus(function(){$(this).css('background','#E0E4F9')}).blur(function(){$(this).css('background','#fff')})
				$('.upper').keyup(function(){$(this).val($(this).val().upper())})
				$('.lower').keyup(function(){$(this).val($(this).val().lower())})				
				$('.tr').mouseover(function(){bgcolor=$(this).css('background-color');
					$(this).css('background-color','#f00');})
						.mouseout(function(){$(this).css('background-color',bgcolor)})
				$('.numeric').keypress(function(event){if (event.charCode&&(event.charCode<48||event.charCode>57)){alert('Somente números por favor!');event.preventDefault();}});		
		
				if ($('#msg').val()!='' && $('#msg')!= undefined) alert($('#msg').val());

				$('.zebrado tr:odd').addClass('bgGray');
  				$('.zebrado tr:even').addClass('bgWhite');
				})		
			function dialogModal(url, nome, height, width) {
				eval(window.showModalDialog(url, nome,'Resizable:no; DialogHeight:'+height+'px ; DialogWidth:'+width+'px; Edge:raised; Help:no; Scroll:no; Status:no; Center:1;'));
				return false;
				}

		</script>
		
		
		<style type="text/css">			
			.menutopo{text-align:right;padding:0 8px}
			.menutopo a{font-size:11px;color:#000;text-decoration:none}						
			.menutopo a:hover{color:#3261B2;text-decoration:underline}
			.menutopo img{width:36px}
			.wellcome{background:#def2f5;padding:4px;color:#058;text-align:center;font-size:12px}	
			/* End */
		</style>
	</head>

	<body style="background:#e4e4e4">
		<div id="content" style="width:1000px;margin:0 auto;border:0;background:#fff;padding:0">
			<input type="hidden" id="msg" value="<?=$this->message?>"/>
			
			<table class="layout" cellpadding="0" cellspacing="0" border="0" width="100%">
				<tr>
					<td>
						<img src="<?=$this->baseImg?>/logoEmpresa.jpg" border="0" width="300"/>
					</td>
				</tr>
				<tr>
					<td>
						<p class="wellcome"><?= $this->fc->date2str(date('d/m/Y'), true)?></p>
					</td>
				</tr>
			</table>
			
			
			
			
			
			
			<style>
				body{font-family:Arial}
				.menulateral{width:172px;padding:4px 0;background:#def2f5;border:solid 1px silver}
				.menulateral div{font-size:13px;color:#808080;width:166px;margin:2px 0;border-bottom:solid 1px #599da1;padding:3px;font-size:12px}
				.menulateral .label{background:#599da1;color:#fff;text-align:center;font-size:12px;border:0}
				.menulateral a{text-align:left;font-size:12px;color:#058;text-decoration:none;white-space:nowrap}
				.menulateral a:hover{color:#599da1;text-decoration:none}
			</style>

			<table class="layout" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:16px 0">		
				<tr>
					<td class="menulateral" valign="top" width="172">
						<div><a href="http://www.amfar.com.br/site/">Ir para o Site Principal</a></div>
						
						<div class="label">CADASTRO</div>						
						<div><a href="<?=$this->baseUrl?>/cadastros/list/">Cadastros Geral</a></div>
						<div><a href="<?=$this->baseUrl?>/cadastros/list/st/1/">Cadastros Associados</a></div>
						<div><a href="<?=$this->baseUrl?>/cadastros/list/st/3/">Membros da Diretoria</a></div>
						<div><a href="<?=$this->baseUrl?>/cadastros/list/st/4/">Cadastros Fornecedores</a></div>
						<!--
						<div class="label">DIRETORIA</div>						
						<div><a href="<?=$this->baseUrl?>/diretoria/list/">Diretoria Atual</a></div>
						<div><a href="<?=$this->baseUrl?>/agenda/list/">Agenda da Diretoria</a></div>
						
						<div class="label">NOTÍCIAS</div>
						<div><a href="<?=$this->baseUrl?>/noticias/">Notícias do Setor</a></div>
						-->
						<div class="label">CURSOS AMF</div>
						<div><a href="<?=$this->baseUrl?>/cursos/list/">Agenda de Cursos</a></div>
						<div><a href="<?=$this->baseUrl?>/cursos/inscricoes/">Cursos - Inscrições</a></div>
						<div><a href="<?=$this->baseUrl?>/cursos/monitores/id/158/">Inscrições Monitores</a></div>
						
						<div class="label">Reserva de Vagas 2013</div>
						<div><a href="<?=$this->baseUrl?>/cursos/reservas/cs/SP/">Saúde Pública</a></div>
						<div><a href="<?=$this->baseUrl?>/cursos/reservas/cs/FH/">Farmácia Hospitalar</a></div>
						<div><a href="<?=$this->baseUrl?>/cursos/reservas/cs/FC/">Farmacolgia Clínica</a></div>
						
						<div class="label">F I N A N C E I R O</div>
						<div><a href="<?=$this->baseUrl?>/financeiro/despesas/">Inserir Despesas</a></div>
						<div><a href="<?=$this->baseUrl?>/financeiro/listdesp/">Listar Despesas</a></div>
						<div><a href="<?=$this->baseUrl?>/boletos/search/">Baixar Boletos</a></div>
						<div><a href="<?=$this->baseUrl?>/financeiro/list/st/1/">Listar Contas a Pagar</a></div>
						<div><a href="<?=$this->baseUrl?>/financeiro/list/st/2/">Listar Contas a Receber</a></div>
						<div><a href="<?=$this->baseUrl?>/financeiro/list/st/3/">Listar Contas Pagas</a></div>
						<div><a href="<?=$this->baseUrl?>/financeiro/list/st/4/">Listar Contas Recebidas</a></div>
						<div><a href="<?=$this->baseUrl?>/financeiro/list/st/5/">Balanço Periódico</a></div>
						
						<div class="label">SAIR DO ADMINISTRATIVO</div>
						<div><a href="<?=$this->baseUrl?>/auth/logout">Encerrar seção</a></div>

						<div class="label">ACESSAR E-MAIL</div>
						<div><a href="http://webmail.amfar.com.br" target="_webmail">Webmail</div>
					</td>
						
					<td width="14"><img src="<?=$this->baseImg?>/space.png" border="0" width="14" /></td>
						
					<td valign="top" style="text-align:left;background:#fff">
						<table cellpadding="0" cellspacing="0" border="0" width="100%" style="font-size:13px">
							<tr>
								<td style="padding:2px;background:#def2f5;color:#058;font-size:14px">
									<img src="<?=$this->baseImg?>/icnave.png" border="0" style="margin-right:12px" />
									<?=$this->where?></td>
								<td style="text-align:right;padding:4px;background:#def2f5;color:#058;vertical-align:bottom">
									<?=($this->user-nome)? "Logado: ".$this->user->nome : ''?>
								</td>
							</tr>
							<tr bgcolor="#ffffff">
								<td colspan="2" style="padding:16px 0">
									<?php echo $this->layout()->content;?>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			
			<table cellpadding="0" cellspacing="0" border="0" id="where" width="100%"
				style="margin:0; padding:0;background:#def2f5;color:#fff;font-size:12px;font-weight:normal;border-top:solid 1px #599da1">
				<tr>
					<td style="text-align:center;padding:4px 2px;color:#000">
						&copy; <?=date('Y')?> by  Associação Mineira de Farmacêuticos - Av. do Contorno, 9215 - Sl 502 - Ed. Humberto Martins Vieira - Prado - 30110-130 - BH/MG<br />
						<span style="font-size:16px">Tel/Fax: 31 3291 6242 - secretaria@amfar.com.br</span>
						<P style="text-align:right"><small>Desenvolvido e mantido por LAB GRAPHIC 11 4184-9311</small><p>
					</td>
				</tr>
			</table>
		</div>		
	</body>
</html>
