<?php
//$this->fc->debug($_POST);
?>

<link type="text/css" href="<?=jsLib?>/themes/base/ui.all.css" rel="stylesheet" />
<script type="text/javascript" src="<?=jsLib?>/ui/ui.datepicker.js"></script>
<script type="text/javascript" src="<?=jsLib?>/ui/ui.core.js"></script>
<link type="text/css" href="<?=$this->baseCss?>/demos.css" rel="stylesheet" />
	
<script>
	$(document).ready(function(){
		$('.data').datepicker({  
			dateFormat: 'dd/mm/yy',  
			dayNames:['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],  
			dayNamesMin:['D','S','T','Q','Q','S','S','D'],  
			dayNamesShort:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],  
			monthNames:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],  
			monthNamesShort:['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],  
			nextText:'Próximo',prevText: 'Anterior'
			});

			
		$('#btSave').click(function(){
			if($('#data').val()==''){alert('Digite a data da agenda!');$('#data').focus();return false;}
			//if($('#userId').val()==''){alert('Selecione o(a) diretor(a)!');$('#userId').focus();return false;}
			updateTextArea('descricao');
			if($('#descricao').val()==''){alert('Digite a descrição da agenda!');$('#descricao').focus();return false;}
			return true;
			})
			
		})

	// settings para o editor		
	var imagesDir = "<?=jsLib?>/wysiwyg/icons/"; // Images Directory
	var cssDir = "<?=jsLib?>/wysiwyg/styles/";	// CSS Directory
	var popupsDir = "<?=jsLib?>/wysiwyg/popups/";	// Popups Directory
	var wysiwygWidth = 570;
	var wysiwygHeight = 250;	// WYSIWYG Width and Height
</script>		
<script type="text/javascript" src="<?=jsLib?>/wysiwyg.js"></script>
<style>
	.table{width:100%;font-size:12px}
	.table th{background:#def2f5;padding:4px;text-align:right}
	.table td{border:solid 1px silver; padding:2px}	
	.table .text {width:400px;border:solid 1px #369;padding:2px}
	.table .data{width:100px;text-align:center}
	.table .curriculo{height:200px}
</style>

<form name="fAgenda" id="fAgenda" method="POST" action="<?=$this->baseSave?>/<?=$this->id?>" ENCTYPE="multipart/form-data">		
	<input type="hidden" id="msg" value="<?=$this->message?>"/>
	<table class="table" class="list" cellpadding="2" cellspacing="2" border="0" width="100%">
		<tr>
			<td colspan="2" style="border:0;text-align:right">
				<a href="<?=$this->baseUrl?>/diretoria/list"><img src="<?=$this->baseImg?>/Undo.png" border="0" /></a></td>
		</tr>
		<tr>
			<th>ID Cadastro</th>
			<td><?=sprintf("%06d",$_POST['idCadastro'])?></td>
		</tr>
		<tr>
			<th>Nome</th>
			<td><?=$_POST['nome']?></td>
		</tr>
		<tr>
			<th valign="top">Foto</th>
			<td>
				<img src="/site/public/diretoria/<?=$_POST['foto']?>" border="0" /><br />
				<input type="file" name="foto" id="foto" />			
			</td>
		</tr>
		<tr>
			<th valign="top">Mini-Currículo</th>
			<td>
				<textarea class="text curriculo" name="curriculo" id="curriculo" maxlength="2048"><?=$_POST['curriculo']?></textarea>						
				<script>generate_wysiwyg('curriculo')</script>
			</td>
		</tr>
		<tr>
			<td colspan="4" style='text-align:center;border:0'>
				<input type="image" name="btSave" id="btSave" src="<?=$this->baseImg?>/btOut.png" 
					onmouseover= "this.src='<?=$this->baseImg?>/btOver.png'"
					onmouseout = "this.src='<?=$this->baseImg?>/btOut.png'"/>
			</td>
		</tr>
	</table>
</form>
