<?php $rs = $this->news ?>
<style>
	.destaque{font-size:20pt;color:#f90;font-weight:bolder}
	.noticias{font-size:12px;color:#000;text-align:justify;padding:4px 0;border-bottom:solid 1px silver}
	.noticias img{text-align:center}
	.noticias .titulo{font-size:14px}
	.noticias .subtitulo{font-style:italic;color:#a4a4a4}
	.noticias .legenda{font-size:10px}
	.noticias .info{float:right;font-weight:bolder;font-size:9px}
</style>

<table class="noticias" border="0" cellpadding="2" cellspacing="0">
	<tr>			
		<td rowspan="2">
			<img src="<?=$this->baseUrl?>/public/news/<?=$rs->foto?>" border="0"><br />
			<span class="legenda"><?=$rs->legenda?></span>
			<span class="info"><?=$rs->fotografo?></span>
			<span class="info"><?=(!empty($rs->fotografo)) ? "Foto $rs->fotografo" : null?></span>
		</td>
		<td>
			<?=$rs->materia?><br />
			<span class="info">
				<?=($rs->fonte) ? "Fonte: $rs->fonte" : null?><br />
				<?=($rs->creditos) ? "Creditos: $rs->creditos" : null?><br />
				<?=($rs->link) ? "Link Original: <a href='$rs->link' target='_blank'>$rs->link</a>" : null?>
			</span>
		</td>
	</tr>
</table>
