<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>AMF - Associação Mineira de Farmacêuticos</title>
		<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
		<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl?>/public/styles/style.css" />	
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery-1.3.2.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/prototypes.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery.maskedinput-1.2.2.min.js"></script>
		<script type="text/javascript" type="text/javascript" src="<?=jsLib?>/jquery.limit-1.0.source.js"></script>
		<link id="lnkRelShortCutIcon" rel="shortcut icon" href="<?=$this->baseImg?>/favicon.png" />
		<style>
			body{overflow:hidden}
			#tbBoleto td{padding:2px;font-size:13px;font-weight:bolder;border:solid 1px #E0E4F9}
			#tbBoleto .label{text-align:right;font-weight:normal;color:#a4a4a4;background:#E0E4F9}
			#tbBoleto .valor{text-align:right}
			#tbBoleto .data{text-align:center}
			#tbBoleto .text{width:100%}
		</style>
		
		<script language="javascript">
			$(document).ready(function(){
				$('.lower').keyup(function(){$(this).val($(this).val().lower())})
				$('#btEnviar').click(function(){
					if($('#email').val().trim() == ''){
						alert("Preencha o campo email!\n\n");
						$('#email').focus();
						return false;
						}
					})
				if ($('#msg').val()!='' && $('#msg')!= undefined) alert($('#msg').val());
				})
		</script>
	</head>
	<body>
		<form name="boleto" method="POST" action="">
			<input type="hidden" id="msg" value="<?=$this->message?>" />
			<table id="tbBoleto" border="0" cellspacing="2" cellpadding="2" width="100%">
				<tr bgcolor="#E0E4F9">
					<td colspan="6"><b>DADOS DO SACADO</b></td>
				</tr>
				<tr>
					<td class="label">Nome:</td>
					<td colspan="5"><b><?=$this->boleto->nome?></b></td>
				</tr>
				<tr>
					<td class="label">CPF/CNPJ:</td>
					<td colspan="5"><b><?=$this->boleto->cpf?></b></td>
				</tr>
				<tr>
					<td class="label" valign="top">Endereço:</td>
					<td colspan="5"><b><?=$this->boleto->ender?></b></td>
				</tr>
				<tr>
					<td align="center" colspan="6" style="border:0">&nbsp;</td>
				</tr>		
				<tr bgcolor="#E0E4F9">
					<td colspan="6"><b>DADOS DO BOLETO</td>
				</tr>
		
				<tr>
					<td class="label">Num. Doc:</td>
					<td><?=$this->boleto->numDoc?></td>
					<td class="label">Valor: R$</td>
					<td><?=number_format($this->boleto->total,2,',','.')?></td>
					<td class="label">Vcto:</td>
					<td><?=$this->fc->Ymd2dmY($this->boleto->vcto)?></td>
				</tr>
				<tr>
					<td class="label">Referente:</td>
					<td colspan="6"><?=$this->boleto->historico?></td>
				</tr>
				<tr>
					<td align="center" colspan="6" style="border:0">&nbsp;</td>
				</tr>
				<tr bgcolor="#E0E4F9">
					<td align="center" colspan="6">Enviar boleto para o email abaixo:</td>
				</tr>
				<tr>
					<td class="label">E-mail:</td>
					<td colspan="5">
						<input type="text" class="text lower" name="email" id="email" maxlength="80" value="<?=$_POST['email']?>" />
					</td>					
				</tr>
				<tr>
					<td align="center" colspan="6" style="border:0">&nbsp;</td>
				</tr>
				<tr bgcolor="#E0E4F9">
					<td align="center" colspan="6">
						<input type="submit" name="btEnviar" id="btEnviar" value=" Enviar boleto anexo " class="button" />
					</td>
				</tr>
			</table>
		
		</form>
	</body>
</html>
