<style>
	.cursos {;border-collapse:collapse;border-color:black}
	.cursos th {background:#369;color:#fff;font-weight:bolder;font-size:11px;text-align:center}
	.cursos td {padding:2px 4px;font-size:13px}
	.cursos td a{color:#000;text-decoration:none;padding:2px 0}
	.cursos td a:hover{font-weight:normal;color:#888;text-decoration:underline}
	.cursos tfoot{font-size:13px}
	.trcursos {background:#ddd}
</style>

<script>
	$(document).ready(function(){
		$('.trcursos:even').css('background','#fff');
		})
</script>

<table width='100%' class='cursos' border='1' cellpadding='2' cellspacing='0'>
	<thead>
		<tr>
			<th>In&iacute;cio</th>
			<th>Curso</th>
		</tr>
	</thead>
	<tbody><?	
		foreach($this->cursos as $rs):
			if(!$rs->inicio)
				$rs->inicio = "Aguarde";
			else
				$rs->inicio = $this->fc->Ymd2dmY($rs->inicio); 	
			echo"
			<tr class='trcursos'>
				<td style='text-align:center;padding:0 4px'>$rs->inicio</td>
				<td><a href='$this->links/open/id/$rs->idCurso/'>$rs->titulo</a></td>
			</tr>";
		endforeach; ?>

		<tr>
			<td colspan="2" style="padding:10px 0 0 10px">
				<p style='text-align:center;font-size:16px;font-weight:bolder'><u>Informa&ccedil;&otilde;es Gerais</u></p>
				
				<p style="display:none">As inscri&ccedil;&otilde;es j&aacute; est&atilde;o abertas - <b>Vagas Limitadas</b></p>
				
				<p style='background:none'>Prezado Usuário,</p>
				
				<p style='background:none;text-align:justify'>Aproveitamos para reafirmar o nosso compromisso e empenho em manter a qualidade do serviço 
					oferecido pela Associação Mineira de Farmacêuticos em parceria com o Centro Universitário Newton Paiva, que tem o 
					reconhecimento e respeito da comunidade acadêmica a nível nacional.</p>
				
				
				<p><b style='color:red'>Para assegurar a sua vaga junto a AMF, você deverá:</b>
					<ol style='margin-top:0'>
						<li>Preencher a ficha de inscrição;</li>
						<li><b>Imprimir e pagar o boleto</b> referente à primeira parcela (nos casos de cursos com pagamento parcelado);</li>
						<li><b>Imprimir e assinar o contrato de prestação de serviços</b> (para cursos de especializações);</li>
						<li><b>Enviar para a AMF</b> os documentos necessários para efetivar a matrícula:<br />
							<b>Contrato assinado<br />
							Currículo Vitae mais histórico escolar da graduação<br />
							Uma foto 3 x 4<br />
							Cópia do Certificado de Graduação Autenticada<br />
							Cópia do CPF e Cópia do RG</b>					
						</li>
						<li><b style='color:red'>Caso o pagamento da primeira parcela para cursos de especialização 
							não seja pago dentro do prazo estipulado, a inscrição será cancelada sem qualquer aviso; 
							exceto nos casos de negociação prévia do aluno com a AMF antes do prazo estipulado.</b>;
						</li>
					</ol>
				</p>
				<p><b style='color:red'>As vagas serão reservadas somente para inscrições efetivadas até 15 dias antes 
					do início do curso. Após este prazo não aceitaremos qualquer reclamação ou solicitação de 
					prorrogação para pagamento.</b></p> 
				<p>Os certificados s&oacute; ser&atilde;o entregues aos alunos caso os mesmos tenham 
					no m&iacute;nimo 75% de freq&uuml;&ecirc;ncia no curso.</p>
				<p>A AMF reserva-se o direito de cancelar os cursos caso não haja número mínimo de participantes.</p>
				
				<p style='text-align:center;font-size:16px;font-weight:bolder;margin:20px 0'><u>Estamos esperando por você!</p>
			</td>
		</tr>
	</tbody>
</table>
		
