<style>
	.vagas{font-size:13px}
</style>

<table class="vagas" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td align="center"></td>
		<td height=25 style="padding:4px 10">						
			<p align=justify>
				<b>ATENÇÃO:</b><span class=texto> As vagas aqui mencionadas são de responsabilidade dos hospitais anunciantes, 
				isentando a SBRAFH sobre qualquer responsabilidade que venha a acarretar no futuro. 
				Este é somente um serviço que disponibilizamos gratuitamente para recolocação profissional.
				Todos os contatos devem ser feito diretamente com o Hospital solicitante. 
				A relação de vagas será apresentada por ordem de entrada.</span>
		</td>
	</tr>

	<tr>
		<td colspan='2'><hr size="1"></td>
	</tr>
</table>
