<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1" />
		<title>AMF - Associação Mineira de Farmacêuticos - Área Restrita</title>
		<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseCss?>/style.css" />
		<script type="text/javascript" src="<?=jsLib?>/jquery-1.3.2.js"></script>
		<script>
			$(document).ready(function(){
				})
		</script>
		<style>
			*{font: 12px Arial, Helvetica, Sans-Serif, Tahoma, Verdana;color:blue}
			.list{width:auto}
			p.pb {page-break-after:always}
			.list caption{background:#369;color:#fff;font-size:16px;padding:4px}
			.list th{background:#369;color:#fff;border:solid 1px #fff}
			.list td{padding:4px;border:solid 1px silver;color:#000}
			.list .right{text-align:right}
			.list b{color:#000;font-weight:bolder}		
		</style>	
	</head>

	<body>
		<table class='list' cellpadding='2' cellspacing='1' border='0'>
			<caption><?=$this->caption?></caption>
			<thead>
				<tr>
					<th>Vcto</th>
					<th>Numdoc</th>
					<th>Histórico</th>
					<th>Valor R$</th>
					<th>Pgto</th>
				</tr>
			</thead>
			<tbody><?
				$count = 0;
				$total=0;			
				foreach($this->dbtable as $row) :
					$count++;
					$bg = ($count % 2 == 0) ? '#b5cbe1':'#ffffff';
					$vcto = $this->fc->Ymd2dmY($row->vcto);
					$pgto = ($row->pgto) ? $this->fc->Ymd2dmY($row->pgto) : '00/00/0000';
					$valor = number_format($row->valor,2,',','.');
					echo"
					<tr bgcolor='$bg'>
						<td width='50'>$vcto</td>
						<td>$row->numDoc</td>
						<td class='left'>".substr($row->historico, 0, 60)."</td>
						<td class='right'>$valor</td>
						<td width='50'>$pgto</td>
					</tr>";
	
					$total += $row->valor;
				endforeach; ?>						
				<tr>
					<td colspan='3' class='right'><b>Total  R$</b></td>
					<td class='right'><b><?=number_format($total,2,',','.')?></b></td>
					<td></td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
