<style>
	* {
		font: 9pt Arial, Helvetica, sans-serif, Verdana;
		color:#004f6d;
		}

	#topo {
		background:url('$_coSite/e-mailing/images/topoEmail.png') no-repeat;
		height:100px;
		padding:44px 0 0 125px;
		font: bolder 18pt Arial, Helvetica, sans-serif, Verdana;
		color:#ffffff;
		text-align:center;
		}


	p, td {
		font: 9pt Verdana, Arial, Helvetica, sans-serif;
		color: #808080
		}


	a {
		font: bolder 9pt Arial, Verdana;
		color:#fe9900;
		text-decoration:none
		}

	a:hover {
		color:#c40000;
		text-decoration:underline;
		font-weight:bolder
		}

	.titulo {
		padding:44px 0 0 125px;
		font: bolder 14pt Arial, Helvetica, sans-serif, Verdana;
		color:#ffffff;
		text-align:center;
		}

	.data {
		padding:0 4px;
		margin:0;
		font: bolder 10pt Arial, Helvetica, sans-serif, Verdana;
		text-align:right;
		background:#f0f0f0;
		}

	#corpo {
		border-left:1px solid #004d6f;
		border-right:1px solid #004d6f;
		text-align:center;
		background:#f0f0f0;
		}

	#rodape {
		background:#a0a0a0;
		text-align:center;
		font: bolder 10pt Arial, Helvetica, sans-serif, Verdana;
		color:#000;
		height:20px;
		background:url('$_coSite/e-mailing/images/rodapeEmail.png') no-repeat;
		}

	#rodape a {
		font: bolder 9pt arial, verdana;
		color:#efefef; font-size:9pt;
		text-decoration:none
		}

	#rodape a:hover {
		color:#fff;
		text-decoration:none;
		border-bottom:1px solid #c40000
		}
</style>